### ISSUE TITLE
Selecting element using attribute not working

### ISSUE THREAD

**Issue by svadla-oc** [OpenClinica/xpath-evaluator-app#4]
When I try to select an xml element using an attribute, I get a blank string as result.
To reproduce:
Evaluate the expression: "/data/a[@id='1']" against the attached test.xml file.

[test.xml.zip](https://github.com/OpenClinica/xpath-evaluator-app/files/4013056/test.xml.zip)

**Comment by MartijnR** [comment]
This is quite mysterious. Thank you. Will figure this out!

**Comment by svadla-oc** [comment]
Thank you!

**Comment by MartijnR** [comment]
The XPath evaluator was not 'bound' correctly to the XMLDoc.

**Comment by svadla-oc** [comment]
Martijn - Thanks for fixing the issue. The previously reported test is working now. However, a more complex expression like the one below doesn't seem to be working correctly against the attached ODM file.  It seems like the tool doesn't like mixed-case attribute names. 

Expression: "/ODM/ClinicalData/SubjectData/StudyEventData[@StudyEventOID='SE_BASELINE']/FormData[@FormOID='F_DEMOGRAPHICS']/ItemGroupData[@ItemGroupOID='IG_DEMOG_GROUP2']/ItemData[@ItemOID='I_DEMOG_DIAGNOSED']/@Value"

[odm.xml.zip](https://github.com/OpenClinica/xpath-evaluator-app/files/4020049/odm.xml.zip)

**Comment by MartijnR** [comment]
Probably something to do with XML parsing.

No, it's not. The JSDOM built-in XPath evaluator has this problem: https://github.com/jsdom/jsdom/issues/2530. However, we're not using that one. So this may still be an issue with how the new evaluator overwrites the 'native' one.

~~It looks like the issue is with Enketo's XPath evaluator. I wonder if this is an undiscovered bug (and that our mixed use of the native XPath evaluator has failed to discover this so far.~~

* [x] check enketo-xpathjs - No problem

**Comment by MartijnR** [comment]
Any custom ODK and OC functions are no longer working. So it's reverting to the JSDOM xpath evaluator, and not Enketo's.

**Comment by MartijnR** [comment]
* [x] try different DOMParser - not dom-parser
* [x] try XMLDom - works
* [x] fix OC XPath extensions
* [x] fix capitalized attributes (because those are not working - check new DOM Parser)

**Comment by MartijnR** [comment]
Trying to do this in a minimal nodeJS environment (without running in a headless browser) is a little trickier than I thought. It's fixed now. Hopefully, that was the last such issue... Thankfully, the fix actually made the app simpler.
